### ISSUE TITLE
ODP instead of ODX?

### ISSUE THREAD

**Issue by jnweiger** [ONLYOFFICE/e2ee_issues#1]
The readme says:

`Support for all key formats: DOCX, XLSX, PPTX, ODT, ODS, ODX, PDF;`

The expected enumeration of open document formats would be ODT, ODS, ODP -- I haven't seen ODX before -- it could be meant as a catch all for all ODx formats, but that is also uncommon and makes not much sense here.

**Comment by ShockwaveNN** [comment]
I think it's a typo for ODP, I'll fix it, thanks
